/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectoordenamientointerno;

/**
 *
 * @author David Arteaga (Art3-)
 */
public class GUIOrdenamientosAdri extends javax.swing.JFrame {

    /** Creates new form GUIOrdenamientoBurbuja */
    public GUIOrdenamientosAdri() {
        initComponents();
        
        //Inicio de los componentes
        //Se pasan los datos en el constructor.
        
        
        
        //Se procede a analizar el tipo de ordenamiento que deseamos
        MetodosDeOrdenamiento metAOrdenar = new MetodosDeOrdenamiento();
        
        
        //Se analiza que tipo de ordenamiento es, y se modifica el titulo
        if(MenuPrincipalAdri.tipoDeOrdenamiento.equalsIgnoreCase("burbuja")){
            lblTituloGUIOrdenamientos.setText("MÉTODO BURBUJA");
            metAOrdenar.metodoBurbuja(MenuPrincipalAdri.vector);
            //System.out.println("burbuja");
        }else if(MenuPrincipalAdri.tipoDeOrdenamiento.equalsIgnoreCase("seleccion")){
            lblTituloGUIOrdenamientos.setText("ORDENAMIENTO POR SELECCIÓN");
            metAOrdenar.ordenamientoPorSeleccion(MenuPrincipalAdri.vector);
            //System.out.println("seleccion");
        }else if(MenuPrincipalAdri.tipoDeOrdenamiento.equalsIgnoreCase("insercion")){
            lblTituloGUIOrdenamientos.setText("ORDENAMIENTO POR INSERCIÓN");
            metAOrdenar.ordenamientoPorInsercion(MenuPrincipalAdri.vector);
            //System.out.println("insercion");
        }else{
            lblTituloGUIOrdenamientos.setText("ORDENAMIENTO QUICKSORT");
            metAOrdenar.ordenamientoQuickSort(MenuPrincipalAdri.vector, 0, MenuPrincipalAdri.vector.length-1);
            //System.out.println("quicksort");
        }
        
        
        int tam = metAOrdenar.getGuardarOrdenamientos().size();
            String matriz [][] = new String [tam][9];
            
            for(int i = 0; i< tam; i++){
                matriz[i][0] = Integer.toString((metAOrdenar.getGuardarOrdenamientos().get(i))[0]);
                matriz[i][1] = Integer.toString((metAOrdenar.getGuardarOrdenamientos().get(i))[1]);
                matriz[i][2] = Integer.toString((metAOrdenar.getGuardarOrdenamientos().get(i))[2]);
                matriz[i][3] = Integer.toString((metAOrdenar.getGuardarOrdenamientos().get(i))[3]);
                matriz[i][4] = Integer.toString((metAOrdenar.getGuardarOrdenamientos().get(i))[4]);
                matriz[i][5] = Integer.toString((metAOrdenar.getGuardarOrdenamientos().get(i))[5]);
                matriz[i][6] = Integer.toString((metAOrdenar.getGuardarOrdenamientos().get(i))[6]);
                matriz[i][7] = Integer.toString((metAOrdenar.getGuardarOrdenamientos().get(i))[7]);
                //Analisis
                if(i<metAOrdenar.getGuardarAnalisis().size()){
                    matriz[i][8] = metAOrdenar.getGuardarAnalisis().get(i);
                }else{
                    matriz[i][8] = "Vector Ordenado";
                }
                
            }
            
            tableBurbuja.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String [] {
                    "[0]", "[1]", "[2]", "[3]", "[4]", "[5]", "[6]", "[7]", "Datos"
                }
            ));
       
            
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloGUIOrdenamientos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBurbuja = new javax.swing.JTable();
        btnRegresarBurbuja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloGUIOrdenamientos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTituloGUIOrdenamientos.setForeground(new java.awt.Color(0, 0, 102));
        lblTituloGUIOrdenamientos.setText("ORDENAMIENTO DEL VECTOR");

        tableBurbuja.setAutoCreateRowSorter(true);
        tableBurbuja.setBackground(new java.awt.Color(242, 251, 252));
        tableBurbuja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "[0]", "[1]", "[2]", "[3]", "[4]", "[5]", "[6]", "[7]", "Datos"
            }
        ));
        tableBurbuja.setRowHeight(30);
        jScrollPane1.setViewportView(tableBurbuja);

        btnRegresarBurbuja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegresarBurbuja.setForeground(new java.awt.Color(0, 0, 102));
        btnRegresarBurbuja.setText("REGRESAR");
        btnRegresarBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarBurbujaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTituloGUIOrdenamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegresarBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloGUIOrdenamientos)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresarBurbuja, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarBurbujaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuPrincipalAdri().setVisible(true);
    }//GEN-LAST:event_btnRegresarBurbujaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIOrdenamientosAdri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIOrdenamientosAdri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIOrdenamientosAdri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIOrdenamientosAdri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIOrdenamientosAdri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarBurbuja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloGUIOrdenamientos;
    private javax.swing.JTable tableBurbuja;
    // End of variables declaration//GEN-END:variables

}
